name: Deploy a Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Surge
        run: npm install -g surge

      - name: Desplegar en Surge
        run: surge ./ --Parcial1paginaweb.surge.sh --token ${{ secrets.SURGE_TOKEN }}
